
sf = readtable('~/Documents/sci.csv','ReadVariableNames',false);
sf.Var2 = strrep(lower(sf.Var2),' ','');
[~,order] = sort(sf.Var2);
sf = sf(order,:);
dup = find(cellfun(@isequal, sf.Var2(1:end-1),sf.Var2(2:end)));
sf(dup,:) = [];
sf(35,:) = [];
fan = readtable('~/Documents/fan.csv','ReadVariableNames',false);
fan.Var2 = strrep(lower(fan.Var2),' ','');
[~,order] = sort(fan.Var2);
fan = fan(order,:);
dup = find(cellfun(@isequal, fan.Var2(1:end-1),fan.Var2(2:end)));
fan(dup,:) = [];
fan.Var2{38} = 'wonder';
fan.Var2{38} = 'silver';
[~,order] = sort(fan.Var2);
fan = fan(order,:);
ismember(fan.Var2,sf.Var2)
list = [fan;sf];
tm = escape_freq(list.Var2)
tm = tm(301:end,:)

list.Properties.VariableNames(1:2) = {'Heb','Eng'};
list.Category = [repmat({'Fantasy'},height(fan),1);repmat({'SciFi'},height(sf),1)];
list.EscapePod = tm.EP;
list.PodCastle = tm.PC;
list.TheNewYorker = tm.NY;
list(isnan(list.EscapePod),:) = [];
m = [mean(list.EscapePod(ismember(list.Category,'SciFi')));...
    mean(list.PodCastle(ismember(list.Category,'SciFi')));...
    mean(list.TheNewYorker(ismember(list.Category,'SciFi')))];
m(:,2) = [mean(list.EscapePod(~ismember(list.Category,'SciFi')));...
    mean(list.PodCastle(~ismember(list.Category,'SciFi')));...
    mean(list.TheNewYorker(~ismember(list.Category,'SciFi')))];
fig = figure;
bar(m)
set(gca,'XTickLabel',{'EscapePod','PodCastle','The New Yorker'},'ygrid','on')
legend('Sci-Fi','Fantasy')
[h,p] = ttest2(list.PodCastle(ismember(list.Category,'SciFi')),list.PodCastle(~ismember(list.Category,'SciFi')))
[h,p] = ttest2(list.EscapePod(ismember(list.Category,'SciFi')),list.EscapePod(~ismember(list.Category,'SciFi')))
title('שכיחות מילים טיפוסיות למדע בדיוני ופנטזיה בשלושה מאגרי סיפורים')
ylabel('שכיחות ממוצעת למילה')
text([1,1.9],[0.11,0.12],{'*','**'})
xlabel(' *  p = 0.08,   **  p = 0.01    מובהקות סטטיסטית    ')
set(gcf,'Color','w')
cd ~/Repos/story_word_count/
saveas(fig,'stats.png')

list.EscapePod = round(list.EscapePod,3);
list.PodCastle = round(list.PodCastle,3);
list.TheNewYorker =  round(list.TheNewYorker,3);
writetable(list,'typical_words.csv','WriteVariableNames',true,'Delimiter',',')
% writetable(tm,'word_freq.csv','delimiter',',','WriteVariableNames',true);

%% old

% scifi = {'חללית';' רובוט';' חייזר';' מחשב';' ננו-';' מדען';' ספינה';' מולקולה';...
%     ' יקום';' חיסון';' נגיף';' סינתוז';' פוזיטרוני';' נפצר';' כפתור';' לייזר';...
%     ' הבזק';' מהירות האור';' מסלול';'קוואנטי';' כוכב';' נחיתה';' מעבדה';' כבידה';...
%     'עתיד';' זמן';' הסתברות';' טכנולוגיה';' שמש';' ירח';' משגר';' מנוע';' ואקום';...
%     ' חליפת חלל';' מחשב';' בינה מלאכותית';' עתיד';' תגלית';' טכנאי';' מתכנת';...
%     ' אסטרונאוט';' טייס';' סוכנות';' אוניברסיטה';' המראה';' מתג';' ידית';' תא טייס';...
%     ' מושב';' חלל';' שנות אור';' רדיו';' תקשורת';' אותות';' סגסוגת';' מחקר';' רכב';...
%     ' רופא';' כוכב לכת';' כפיל';' מוטנט';' גנים';' כוח מחשוב';'DNA';' סילון';...
%     ' הינע';' מנוע';'גלקטי';' ניורוני';' טלפתי';' אמפת';' שער רוזן-פדולסקי';' GPS';...
%     ' טלפורטציה';' חור תולעת';' פוטונים';' פוזיטרונים';' טכיונים';' על-חלל';' אבולוציה';...
%     ' שיבוט';' טלפתיה';' קיבורג';'סייבורג';' אנדרואיד';' הומנואיד';' טלקינזיס ';...
%     ' הסטה לאדום';' הסטה לכחול';' ספקטרום';' קרני אלפא';'בטא';'גמא ';'בתוספת דלתה';'';...
%     ' כל הספקטרום האלקטרומגנטי: רדיו';' מיקרוגל';' אינפרא־אדום';' אולטרא־סגול';...
%     '  רנטגן';'  טיורינג';' ננובוטים';' הנדסה גנטית';' מרחב';' מרחב עקום';...
%     ' לולאת זמן־חלל';' מסע בזמן';' פרדוקס';' גרביטציה';' מחולל גרביטציה';' גרביטציה מלאכותית';...
%     ' חור־לבן';' חור־תולעת';' אופק ארועים';' סינגולריות';' היתוך גרעיני';' איזוטופ';...
%     ' אלוטרופי';' בוזון';' פרמיון';' ספין';' לפטונים';' קוורקים';' חלקיק־';'טאו';' מיואון';...
%     ' אומגה';' נייטרינו וכך הלאה';'';' יריעת רימאן';' יקום מקביל';' פוזיטרון';' מיקרוסקופ';...
%     ' טלסקופ';' ספקטרומטר';' ספקטרוגרף ';'המסות';'';' בקבוק מגנטי';' שדה־כוח';' קרן־גרירה';...
%     ' יונים';' מולקולה';'מהונדס';' חיידק';'ליבה';...
%     ' כור־גרעיני';' הינע';' כוכב';'';'תחנה';' אסטרואיד';' מטאור';' מטאוריט';...
%     'אנרגיה';'גרעיני';' איינשטיין';' הכחדה';' קסנוביולוגיה';' טרפורמינג';'הארצה';...
%     ' ממיר';' מחולל';' marines';'חרב-אור';' מסע בזמן';' מלחמה';' מסע'};
% scifi(cellfun(@isempty,scifi)) = [];
% {'rocket ship';' robot';' Alien';' computer';' Nano- ';' scientist';' ship';' Molecule '; ...
%     'Universe'; ' Vaccine ';' virus';' Synthesis; Positroni ';' Naftar ';' button';' Laser '; ...
%     'Flash'; ' speed of light';' Track ';' Quantum ';' Star';' landing';' Laboratory';' gravitation';...
%     'Future'; ' time';' probability';' technology';' sun';' moon';' launcher';' Engine';' Vacuum '; ...
%     ' space suit';' computer';' artificial intelligence';' Future ';' discovery';' technician';' programmer';...
%     'Astronaut'; ' Pilot ';' agency';' university';' the mirror';' switch';' handle';' Cockpit';...
%     ' Session';' space';' light years';' radio';' communication';' Signals ';' alloy';' Research';' vehicle';...
%     'Doctor'; ' Planet';' stuntman';' mutant';' Gardens ';' Computing power ';' DNA ';' jet';...
%     'Hine'; ' Engine ';' galactic ';' Neurons ';' telepathic';' Empath ';' Rosen-Pedolsky Gate ';' GPS '; ...
%     'Teleportation'; ' Wormhole ';' Photons ';' Positrons ';' Technions ';' On space ';' evolution';...
%     'Clone'; ' telepathy';' Cyborg; Cyborg; Android ';' Humanoid ';' Telekinesis'; ...
%     'Shift to red'; ' Shift to blue ';' spectrum';' Alpha rays'; 'beta'; 'gamma'; 'with the addition of a delta'; ''; ...
%     'All Electromagnetic Spectrum: Radio'; ' microwave';' Infra red';' Ultraviolet '; ...
%     'X-ray'; ' Turing ';' Nanobots ';' Genetic Engineering';' space';' Curved space '; ...
%     'Space-time loop'; ' time travel';' paradox';' gravitation';' Gravity generator ';' Artificial gravity '; ...
%     'White hole'; ' Wormhole ';' Event horizon ';' Singularity ';' Nuclear fusion ';' isotope';...
%     'Allotropic'; ' Boson ';' Fermion ';' Spin ';' For petunias ';' Quarks ';' Particle- ';' Tao ';' Mioon '; ...
%     'Omega'; ' Neutrino and so on ';' ';' Ryman '' sheet ';' Parallel universe';' Positron ';' microscope';...
%     'Telescope'; ' Spectrometer ';' Spectrograph ';' Essays ';' ';' Magnetic bottle ';' forcefield';' Towing Beam '; ...
%     'Pigeons';' Molecule ';' engineered ';' Bacteria ';' core '; ...
%     ' nuclear reactor';' Hine ';' Star ';' ';' Station ';' asteroid';' meteor';' Meteorite '; ...
%     'Energy'; 'Nuclear'; ' Einstein ';' extinction';' Xenobiology ';' Transforming ';' Landing '; ...
%     'Converter'; ' generator';' marines ';' Sword-light ';' time travel';' war';' a journey'};
% scifi =     {'rocket';' robot';' Alien';'computer';' Nano';' scientist';' ship';' Molecule ';'Universe';' Vaccine ';' virus';' Synthesis';'Positron';'bluster';' button';' Laser ';'Flash';'speed';'light';' Track ';' Quantum ';' Star';' landing';' Laboratory';' gravitation';'Future';' time';' probability';' technology';' sun';' moon';' launcher';' Engine';' Vacuum ';' space suit';'computer';'  intelligence';'artificial';' Future ';' discovery';' technician';' programmer';'Astronaut';' Pilot ';' agency';' university';' the mirror';' switch';' handle';' Cockpit';' Session';' space';' light years';' radio';' communication';' Signals ';' alloy';' Research';' vehicle';'Doctor';' Planet';' stuntman';' mutant';' Gardens ';' Computing';' DNA ';'computer';'Hine';' Engine ';' galactic ';' Neurons ';' telepathic';' Empath ';'gate';' GPS ';'Teleportation';' Wormhole ';' Photons ';' Positrons ';' Technions ';'hyperspace ';' evolution';'Clone';' telepathy';' Cyborg';'Android ';' Humanoid ';' Telekinesis';'Shift';' spectrum';' Alpha rays';'beta';'gamma';'radio';' microwave';' Infra';' Ultraviolet ';'ray';' Turing ';' Nanobots ';' Genetic ';'Engineering';' space';' Curved';' paradox';' gravitation';' Gravity generator ';' Artificial gravity ';'White hole';' Wormhole ';' Event horizon ';' Singularity ';' Nuclear fusion ';' isotope';'Allotropic';' Boson ';' Fermion ';' Spin ';' For petunias ';' Quarks ';' Particle';' Tao ';'muon';'Omega';' Neutrino';' Ryman '' sheet ';' Parallel universe';' Positron ';' microscope';'Telescope';' Spectrometer ';' Spectrograph ';' Magnetic ';' forcefield';' Towing  ';'Beam';'ions';' Molecule ';' engineered ';' Bacteria ';' core ';' reactor';'drive';' Star ';' Station ';' asteroid';' meteor';' Meteorite ';'Energy';'Nuclear';' Einstein ';' extinction';' Xenobiology ';'terraforming ';' Landing ';'Converter';' generator';' marines ';' war';'journey'};

% scifi_heb = {'חללית';'רובוט';'חייזר';'מחשב';'ננו';'מדען';'ספינה';'מולקולה';'יקום';'חיסון';'נגיף';'סינתוז';'פוזיטרוני';'נפצר';'כפתור';'לייזר';'הבזק';'מהירות';'האור';'מסלול';'קוואנטי';'כוכב';'נחיתה';'מעבדה';'כבידה';'עתיד';'זמן';'הסתברות';'טכנולוגיה';'שמש';'ירח';'משגר';'מנוע';'ואקום';'חליפת חלל';'מחשב';'בינה ';'מלאכותית';'עתיד';'תגלית';'טכנאי';'מתכנת';'אסטרונאוט';'טייס';'סוכנות';'אוניברסיטה';'המראה';'מתג';'ידית';'תא טייס';'מושב';'חלל';'שנות אור';'רדיו';'תקשורת';'אותות';'סגסוגת';'מחקר';'רכב';'רופא';'כוכב לכת';'כפיל';'מוטנט';'גנים';'מחשוב';'DNA';'סילון';'הינע';'מנוע';'גלקטי';'ניורוני';'טלפתי';'אמפת';'שער';'GPS';'טלפורטציה';'חור תולעת';'פוטונים';'פוזיטרונים';'טכיונים';'על-חלל';'אבולוציה';'שיבוט';'טלפתיה';'סייבורג';'אנדרואיד';'הומנואיד';'טלקינזיס ';'הסטה';'ספקטרום';'קרני אלפא';'בטא';'גמא ';'רדיו';'מיקרוגל';'אינפרא';'אולטרא־סגול';'רנטגן';'טיורינג';'ננובוטים';'גנטית';'הנדסה';'מרחב';'עקום';'פרדוקס';'גרביטציה';'לולאת זמן־חלל';'גרביטציה מלאכותית';'חור־לבן';'חור־תולעת';'אופק ארועים';'סינגולריות';'היתוך גרעיני';'איזוטופ';'אלוטרופי';'בוזון';'פרמיון';'ספין';'לפטונים';'קוורקים';'חלקיק';'טאו';'מיואון';'אומגה';'נייטרינו וכך הלאה';'יריעת רימאן';'יקום מקביל';'פוזיטרון';'מיקרוסקופ';'טלסקופ';'ספקטרומטר';'ספקטרוגרף ';'מגנטי';'שדה־כוח';'גרירה';'קרן';'יונים';'מולקולה';'מהונדס';'חיידק';'ליבה';'כור';'הינע';'כוכב';'תחנה';'אסטרואיד';'מטאור';'מטאוריט';'אנרגיה';'גרעיני';'איינשטיין';'הכחדה';'קסנוביולוגיה';'הארצה';'נחיתה';'ממיר';'מחולל';'marines';'מלחמה';'מסע'};

% 
% fantasy = {'פיה';' קסם';' קוסם';' מכשפה';' מכשף';' מסע';' סוס';' גמד';' טרול';...
%     ' נבואה';'קללה';' עולם ';' הנבחר';'המיועד';' אופל';' הרים';' מערה';' דרקון';...
%     ' חרב';' קשת';' נהר';' גיבור';' הקרבה';' יצירה';' מופלא';' סוד';' מלך';...
%     ' טירה';' מורה דרך';' יער';' דרקון';' לחשים';' טירה';' מבוך';' שיקוי';...
%     'התגלות';'חיזיון';' לחש';' נימפה';' אלף';' גמד';' גובלין';' אורק';' חד קרן';...
%     ' טירה';' חרב';' שריון';' מגן';' אוצר';' תיבה';' שרביט';' מטה';' סוס';' רמך';...
%     ' רומח';' לוחם';' אביר';' נסיכה';' מלך';' מגדל';' קללה';'מאנה';' קוסם';...
%     ' כהן';' גנב';' פלאדין';' נבל';' רב-מג';' דרואיד';' נסיכה';' מתנקש';' ידעוני';...
%     ' ברברי';' מכשף';' קלפים';'תכשיט';'כתר';' מפלצת';' טירה';' קסום';' אגדי';...
%     ' הוביט';' דרקון';' ערפדים';' לילית';' גילדה';'אלים';'קסם';' כישוף';'מגילות';'זהב';' כסף'};
% fantasy = unique(strrep(fantasy,' ',''));
% 
% 
% 
% fan = {'fairy';' magic';' magician';' witch';' sorcerer';' a journey';' horse';' dwarf';' Troll '; ...
%     'Prophecy'; 'curse'; ' World ';' Selected ';' Designated ';' opal';' Mountains ';' cave';' dragon';...
%     'Sword'; ' Rainbow';' river';' Hero ';' sacrifice';' Creation';' marvelous';' secret';' king';...
%     'Castle'; ' guide';' forest';' dragon';' Spells ';' castle';' maze';' potion';...
%     'Revelation'; 'Vision'; ' spell';' nymph';' Thousand';' dwarf';' Goblin ';' Orc ';' Unicorn';...
%     'Castle'; ' sword';' armor';' Protector';' curator';' Box ';' wand';' Down';' horse';' Remach '; ...
%     'Spear'; ' fighter';' knight';' princess';' king';' tower';' Curse ';' Mana ';' magician';...
%     'Cohen'; ' Thief';' Paladin ';' harp';' Multi-maj; ';' Droid ';' princess';' assassin';' Knowledge '; ...
%     'Barbary'; ' sorcerer';' Cards ';' Jewel ';' Crown ';' monster';' castle';' enchanted';' legendary';...
%     'The Hobbit'; ' dragon';' Vampires ';' Lilith ';' Guild ';' Gods ';' Magic ';' Witchcraft ';' Scrolls ';' Gold ';' Of money'};